name: Black
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  Black:
    uses: steinwurf/black-action/.github/workflows/action.yml@2.0.0
