jobs:
  Black:
    uses: steinwurf/black-action/.github/workflows/action.yml@2.0.0
name: Black
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch: null
