name: Tests
on: [push, pull_request]
jobs:
  waf:
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Linux]
    runs-on: [self-hosted, "${{ matrix.os }}"]
    name: ${{ matrix.os }} Test
    env:
      python: python3
    steps:
      - name: Rename python3 to python on Windows
        if: runner.os == 'Windows'
        run: echo "python=python" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: ${{ env.python }} waf configure
      - name: Build
        run: ${{ env.python }} waf
      - name: Test
        run: ${{ env.python }} waf --run_tests
  # Code Format Check
  black:
    name: Black
    runs-on: [self-hosted, docker]
    container:
      image: kiwicom/black
      options: --user 0:0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Black Check
        run: black . --check
