jobs:
  flake8:
    uses: steinwurf/flake8-action/.github/workflows/action.yml@2.0.0
name: Flake8
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch: null
