name: Flake8
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  flake8:
    uses: steinwurf/flake8-action/.github/workflows/action.yml@2.0.0
